name: Run tests

on: [push, workflow_dispatch]

jobs:
  tests:
    name: Automated tests
    runs-on: ubuntu-latest

    env:
      EXAMPLE_VAR: ${{ secrets.EXAMPLE_VAR }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2

      - name: Prepare modules
        run: npm install

      - name: Run push
        if: ${{ github.event_name == 'push'  }}
        run: echo "Running push event"
        
      - name: Run Schedule
        if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
        run: echo "Running schedule"

      - name: Run tests
        run: npm test
