name: Run tests

on: push

jobs:
  tests:
    name: Automated tests
    runs-on: ubuntu-latest

    env:
      EXAMPLE_VAR: ${{ secrets.EXAMPLE_VAR }}

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        # https://github.com/actions/setup-node
        uses: actions/setup-node@v2

      - name: Prepare modules
        run: npm install

      - name: Run tests
        run: npm test
